import React,{useEffect,useRef,useState} from 'react';
import {audioSettings,enableEffects,playEffect,sceneSound} from './audio.js';
export default function AudioControls({text}){
 const [status,setStatus]=useState('idle'),[voices,setVoices]=useState([]),[voiceId,setVoiceId]=useState(''),[volume,setVolume]=useState(()=>audioSettings().volume),[effects,setEffects]=useState(()=>audioSettings().enabled),[notice,setNotice]=useState('');
 const utterance=useRef(null),available=typeof window!=='undefined'&&'speechSynthesis' in window;
 useEffect(()=>{if(!available)return;const sync=()=>setVoices(window.speechSynthesis.getVoices().filter(v=>/^pt/i.test(v.lang)));sync();window.speechSynthesis.addEventListener('voiceschanged',sync);return()=>window.speechSynthesis.removeEventListener('voiceschanged',sync)},[available]);
 useEffect(()=>{setStatus('idle');const cue=sceneSound(text);if(cue)playEffect(cue);return()=>{if(utterance.current&&available){utterance.current.onend=null;utterance.current.onerror=null;window.speechSynthesis.cancel();utterance.current=null}}},[text,available]);
 function stop(){window.speechSynthesis.cancel();setStatus('idle')}
 function speak(){setNotice('');if(status==='speaking'){window.speechSynthesis.pause();setStatus('paused');return}if(status==='paused'){window.speechSynthesis.resume();setStatus('speaking');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text||'').replace(/\*\*/g,''));u.lang='pt-BR';u.rate=.92;u.volume=volume;u.voice=voices.find(v=>v.voiceURI===voiceId)||voices.find(v=>v.lang==='pt-BR')||voices[0]||null;u.onend=()=>setStatus('idle');u.onerror=e=>{setStatus('idle');if(e.error!=='canceled'&&e.error!=='interrupted')setNotice('A voz não está disponível neste navegador. Tente outra voz.')};utterance.current=u;setStatus('speaking');window.speechSynthesis.speak(u)}
 return <details className="audio-controls" onPointerDown={()=>{if(effects)enableEffects(true,volume).catch(()=>{})}}><summary>Narração e efeitos sonoros</summary><div className="audio-buttons"><button disabled={!available} onClick={speak}>{status==='speaking'?'Pausar narração':status==='paused'?'Retomar narração':'▶ Ouvir trecho'}</button><button disabled={!available||status==='idle'} onClick={stop}>Parar</button></div>{available&&voices.length>0&&<label>Voz<select value={voiceId} onChange={e=>{setVoiceId(e.target.value);stop()}}><option value="">Português automático</option>{voices.map(v=><option key={v.voiceURI} value={v.voiceURI}>{v.name}</option>)}</select></label>}<label>Volume<input type="range" min="0" max="1" step=".05" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);enableEffects(effects,v).catch(()=>{});if(status!=='idle')stop()}}/></label><label className="effects-toggle"><input type="checkbox" checked={effects} onChange={async e=>{const on=e.target.checked;try{const ok=await enableEffects(on,volume);setEffects(on&&ok);if(!ok)setNotice('Efeitos indisponíveis neste navegador.');if(on&&ok)playEffect('bell')}catch{setNotice('Não foi possível ativar o áudio.')}}}/>Sons dos acontecimentos</label><small>A chuva continua no controle do cabeçalho. A voz depende das opções disponíveis no navegador.</small>{!available&&<p>Narração indisponível neste navegador.</p>}{notice&&<p role="status">{notice}</p>}</details>;
}
